name: reviewdog
on:
  pull_request:
    paths:
      - '**.ts'
      - '**.tsx'
jobs:
  prettier:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - name: Install package
        run:
          npm install

      - name: Run prettier
        run:
          npm run prettier

      - uses: stefanzweifel/git-auto-commit-action@v2.1.0
        with:
          commit_message: Apply prettier changes
          branch: ${{ github.head_ref }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
